### ISSUE TITLE
Difficulty with microcourse 1.5, AWS integration with MongoDB

### ISSUE THREAD

**Issue by programlich** [AccelerationConsortium/ac-microcourses#108]
For me, this course was one of the more difficult one, because until now, I was completely unfamiliar with any kind of AWS services. This makes the learning curve quite steep, which is nice, but I wonder, if it is really worth it, focusing so much energy on something which is practically only a workaround. To give you an example of the level of knowledge I started with and what kind of errors I made, I'll give you a collection of aspects, which I needed to learn because I was doing them wrong in the first place:
- The mongodb cluster needs to be made available to all IP adresses, to be reachable: 0.0.0.0
- After writing the lambda function, it has to be deployed
- I could not find any pymongo layer for the lampda function, so I had to build it locally on my laptop and upload it to aws
- The connection string for pymongo needs to contain the username and password for the DATABASE USER and not the global Atlas credentials. This should probably be pointed out explicitly, because I guess many people will do it wrong when touching this system the first time
- To have the API gateway working with the API key, the "API key required" must be toggled under API Gateway -> API -> ressources -> POST -> method request -> API key required
- In main.py the `import time` needed to be added. Not sure, if this was on purpose from your side
- For the use of the API key, a usage plan needs to be created and associated with the API key and the API stage
- I spent lots of time trying to figure out, how the body of the requests needs to be formatted. To someone new to the field this kind of formatting is quite confusing. Some extra explanation would be very helpful here (see the code for main.py, which finally worked for me below)

**Comment by programlich** [comment]
Yes, this would definitely be very helpful, at least to a complete newcomer like me!

**Comment by sgbaird** [comment]
> If I get the final step of the course (1.6) right, the mongodb is only part of the setup for logging purposes. All the communication between Pico and Orchestrator run via the MQTT Broker. So I am wondering, if for the sake of simplicity in the Hello World course, we could just move the logging commands to the orchestrator. This way, a comfortable way of logging via pymongo would be possible and the overall result would be the same. The more advanced communication via AWS Gateway could then be introduced in course 2 or 3.

I struggled a lot with this decision during the early implementation period, and I think given the deprecation of the MongoDB Data API, this may be the best route. Moving the AWS Lambda piece to course 3 (robotics) or 4 (software dev.) may make more sense. In particular, there are two major reasons for keeping the AWS Lambda piece:
1. Gaining exposure to AWS in general, and how to have small bits of Python code that can run on-demand without needing to have a dedicated machine for it
2. Show people what they need for streaming time-series data to a database that doesn't depend on an orchestrator running 24/7. In particular, things like temperature/pressure/humidity/gas (https://github.com/AccelerationConsortium/ac-training-lab/issues/13), accelerometer data, or streaming the weight data from a scale, are all potentially useful things to track without having an actively running experimental campaign. "Lab metadata" in a sense.

Like you said, maybe it's too much to have in the hello world course. I think we'll try first with a walkthrough video and reassess.

**Comment by sgbaird** [comment]
After creating a walkthrough, let's consider moving the "direct upload from microcontroller" piece to https://ac-microcourses.readthedocs.io/en/latest/courses/software-dev/4.8-cloud-server.html#serverless-computing, focused on the example of using a temperature/pressure/humidity/gas sensor.

**Comment by kelvinchow23** [comment]
just adding on that i had the same sentiments as Matthias. 
It wasn't easy to get through this module, but I felt it is well worth the torture to go through the exercise of getting some exposure to AWS and some database (although what I am looking to learn may not be what other students taking the course cares about).
it sounds like some of this is still under development so I didn't bother trying to pass this module. I looked into some of the tests and am wasn't sure if it was my scripts or the tests that need updating.
a video walkthrough would have been nice, maybe i should have waited a bit before doing this.
