### ISSUE TITLE
Software Dev Course 4.8

### ISSUE THREAD

**Issue by linx5o** [AccelerationConsortium/ac-microcourses#109]
![image](https://github.com/user-attachments/assets/9208e413-404c-4be2-8eac-5a5b19b28714)
I think more steps should be added. Like what kind of project to choose, verisons, etc. How to upload files.
For Step 3. This would not work in this order, we have not yet uploaded any requirements.txt file to the server. I think this step should be later.

Or maybe put the tutorial first and have a summary of the tutorial below.

**Comment by linx5o** [comment]
Installation of Docker could also be pointed to their site and the installation of the client app with UI, easier to use and manager container for people who are new to using Docker, [Docker Desktop](https://www.docker.com/).

We could also mention the VS code extension for Docker, allows for us to view images etc in VS code.

**Comment by SissiFeng** [comment]
OK, I will refine this part.

**Comment by linx5o** [comment]
For the assignment, 
![image](https://github.com/user-attachments/assets/5ad5d5d4-3b15-440d-8e14-35682e0f28ad)
I don't see how generating random input and outputs will allows us to train a model and draw a correlation. I feel like this dataset is invalid and can't really be used to train a model, any conclusion we could draw would also be just due to luck.

**Comment by SissiFeng** [comment]
This section isn’t intended to teach how to train machine learning models rigorously. The idea is to prevent the assignment from being just a basic calculator project, which could feel dull and uninspiring. By incorporating dummy numbers and random data, the goal is to give students a hands-on feel for the overall data flow and process in a more engaging way. Otherwise, the feedback might be that the task is too difficult, with an overwhelming learning curve right from the start.

That said, if you have suggestions for a balanced approach that would make the assignment both more meaningful and accessible without making it overly complex, I would be happy to incorporate improvements.

**Comment by linx5o** [comment]
> This section isn’t intended to teach how to train machine learning models rigorously. The idea is to prevent the assignment from being just a basic calculator project, which could feel dull and uninspiring. By incorporating dummy numbers and random data, the goal is to give students a hands-on feel for the overall data flow and process in a more engaging way. Otherwise, the feedback might be that the task is too difficult, with an overwhelming learning curve right from the start.
> 
> That said, if you have suggestions for a balanced approach that would make the assignment both more meaningful and accessible without making it overly complex, I would be happy to incorporate improvements.


Ok, I see. I don't see how we could pass the test though. With as target of MSE > 10000.

**Comment by sgbaird** [comment]
How about `make_regression`? https://scikit-learn.org/1.5/datasets/sample_generators.html#generators-for-regression

**Comment by sgbaird** [comment]
For https://ac-microcourses.readthedocs.io/en/latest/courses/software-dev/4.8-cloud-server.html#id8, thoughts on showing a deployment of a Bayesian optimization campaign from Hello World module 1.3 or one of the Data Science modules, deployed to a forever-free-tier Oracle VM? (And mention EC2 and other equivalents)

**Comment by SissiFeng** [comment]
Update the assignment contents and tutorial.
