### ISSUE TITLE
Software Dev Course 4.9

### ISSUE THREAD

**Issue by linx5o** [AccelerationConsortium/ac-microcourses#114]
AWS Lambda is not free. Only for new users, if someone already has an account and has passed the free period then it is not free.

Instead of "go to" I think we can replace with "search for" as AWS has a lot of products which can be a pain to dig through.

**Comment by sgbaird** [comment]
This is what I was going off of, but maybe I'm missing something: https://aws.amazon.com/free/?gclid=CjwKCAjwg-24BhB_EiwA1ZOx8rMjkXhCUCGZhZF6KGyMr2GOtbBD9iFxv6ygfsewYMHfDRIB_n7vUxoCa9MQAvD_BwE&trk=6482fef4-3b65-4bc0-99d1-6b633acd30b6&sc_channel=ps&ef_id=CjwKCAjwg-24BhB_EiwA1ZOx8rMjkXhCUCGZhZF6KGyMr2GOtbBD9iFxv6ygfsewYMHfDRIB_n7vUxoCa9MQAvD_BwE:G:s&s_kwcid=AL!4422!3!677909272508!e!!g!!aws%20free%20tier!20683060497!153526571454&all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=tier%23always-free&awsf.Free%20Tier%20Categories=*all

![Screenshot_20241025-081009.png](https://github.com/user-attachments/assets/ae5a65f0-c329-48e4-96d4-0004db991b69)

**Comment by linx5o** [comment]
> This is what I was going off of, but maybe I'm missing something: https://aws.amazon.com/free/?gclid=CjwKCAjwg-24BhB_EiwA1ZOx8rMjkXhCUCGZhZF6KGyMr2GOtbBD9iFxv6ygfsewYMHfDRIB_n7vUxoCa9MQAvD_BwE&trk=6482fef4-3b65-4bc0-99d1-6b633acd30b6&sc_channel=ps&ef_id=CjwKCAjwg-24BhB_EiwA1ZOx8rMjkXhCUCGZhZF6KGyMr2GOtbBD9iFxv6ygfsewYMHfDRIB_n7vUxoCa9MQAvD_BwE:G:s&s_kwcid=AL!4422!3!677909272508!e!!g!!aws%20free%20tier!20683060497!153526571454&all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=tier%23always-free&awsf.Free%20Tier%20Categories=*all
> 
> ![Screenshot_20241025-081009.png](https://github.com/user-attachments/assets/ae5a65f0-c329-48e4-96d4-0004db991b69)
> 
> 

Yep, I think you are right. It was not showing anything in my free tier part, and when I clicked on lambda costs it just brought to to the actual costs place. Guess I need to do something to activate, or maybe it activates after usage?
