### ISSUE TITLE
Software Dev Course 4.9 Assignment

### ISSUE THREAD

**Issue by linx5o** [AccelerationConsortium/ac-microcourses#115]
![image](https://github.com/user-attachments/assets/4657f58b-af7a-4f7e-adfb-278ea06448ea)
In workflow.py there seems to be a duplication of code

**Comment by linx5o** [comment]
I had error installing the requirements, this might be my issue though. Would like to see if anyone else has a similar issue.

**Comment by linx5o** [comment]
![image](https://github.com/user-attachments/assets/1abb22c6-0ff1-4c37-b5f9-613e9682c68c)
The deployment of workflow did not work. I got `prefect deploy` to work and show option. Maybe a version of Prefect is the issue? I am on version 3.0.11. 

Some more explanation of what is happening here and what we are doing would also be nice.

**Comment by linx5o** [comment]
Point students to [AWS CLI](https://aws.amazon.com/cli/) to download.

**Comment by linx5o** [comment]
![image](https://github.com/user-attachments/assets/9f0dfe93-46b7-43c0-a880-75addbe6e537)
![image](https://github.com/user-attachments/assets/63c47c96-66fc-43c9-b5fc-4042b7eb626d)
Mabye include some picture to help with finding the access key part.

**Comment by sgbaird** [comment]
We should include some clarification about Prefect 2 vs. Prefect 3 (mostly just pointing it out and a link to the docs about (recent) Prefect 3 release). I'll leave the specific errors for Sissi to look at next week.

For the work pool, maybe worth pointing out the free Prefect managed work pool? This is what's typically used when someone is testing things out. Maybe we show how to use with Prefect managed work pool, and then provide links or an example of how to use an EC2 as a work pool?

Often, physics-based simulations can take on the order of minutes, hours, days, etc. It's good that the resource limitations are mentioned in that section, and worth pointing out the AWS Lambda is typically used for very quick to run items.
