### ISSUE TITLE
4.3 Comment - lack of clarity within the statement "Use print statements to debug your implementation" for calculate_average

### ISSUE THREAD

**Issue by sgbaird** [AccelerationConsortium/ac-microcourses#123]
4.3 Comment - lack of clarity within the statement "Use print statements to debug your implementation" for calculate_average. Unclear where to put print statement. If put into the function itself, you get "maximum recursion depth exceeded while calling a Python object." 

![image](https://github.com/user-attachments/assets/01552dc3-4b24-406c-91fc-df1889310c07)

_Originally posted by @RubainaFarin31 in https://github.com/AccelerationConsortium/ac-microcourses/issues/60#issuecomment-2468871641_

**Comment by SissiFeng** [comment]
I updated the README with a detailed guide on exactly what to do. 
<img width="1032" alt="截屏2024-11-11 15 25 45" src="https://github.com/user-attachments/assets/20609b2f-76a0-47b4-9521-78739807c722">
