### ISSUE TITLE
4.4. The repetition of Step 1 and 3

### ISSUE THREAD

**Issue by sgbaird** [AccelerationConsortium/ac-microcourses#124]
> 4.4. The repetition of Step 1 and 3 is a bit confusing! I understand what you mean but I think it can be eliminated altogether — current wording makes it seem like it needs to be implemented twice. 

Additionally, not sure if I misunderstood but, there is no run_tests() function to actually run the tests.

_Originally posted by @RubainaFarin31 in https://github.com/AccelerationConsortium/ac-microcourses/issues/60#issuecomment-2468907135_

**Comment by SissiFeng** [comment]
https://github.com/ACC-SoftwareDev/4.4-Unit-testing/blob/main/README.md

Updated the README file with clearer and straightforward instructions for the assignment.
