### ISSUE TITLE
SSH example with SBC

### ISSUE THREAD

**Issue by sgbaird** [AccelerationConsortium/ac-microcourses#59]
@SissiFeng 

![PXL_20240919_162929367.jpg](https://github.com/user-attachments/assets/64b12e3b-1248-4dc4-94b5-ae185b4e1a7f)

I'm leaving a raspberry Pi Zero 2W kit at the desk. You can use this for the SSH example. I'll double check to see if we have any Raspberry Pi 5 kits around, but this should be enough for a minimal working example.

You can use the monitoring keyboard setup from the desk with the vial capper decapper. 

![PXL_20240919_163101159.jpg](https://github.com/user-attachments/assets/8f265090-41f1-4d9c-9bf0-5f167f53ac22)

**Comment by SissiFeng** [comment]
Done.
