### ISSUE TITLE
bug in as7341_sensor.py?

### ISSUE THREAD

**Issue by programlich** [AccelerationConsortium/ac-microcourses#83]
The as7341_sensor.py in module 1.2 did not work out of the box. In fact I got an error for line 6, saying that the module `machine._machine` did not exist. Removing the `._machine` extension did the trick. The working line looks like:
`from machine import I2C, Pin`

Not sure, why this happens, but I definitely did not get the script running with the unmodified line.

**Comment by sgbaird** [comment]
I see. That looks like a bug on my part: https://github.com/ACC-HelloWorld/2-blink-and-read-programlich/blob/main/lib%2Fas7341_sensor.py#L6.

I think the file directly from self-driving-lab-demo will work (i.e., what gets uploaded during module 1), but I must have done something wonky when putting it in the assignment repo. Will fix.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: programlich ***@***.***>
Sent: Monday, October 7, 2024 3:36:22 PM
To: AccelerationConsortium/ac-microcourses ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AccelerationConsortium/ac-microcourses] bug in as7341_sensor.py? (Issue #83)


The as7341_sensor.py in module 1.2 did not work out of the box. In fact I got an error for line 6, saying that the module machine._machine did not exist. Removing the ._machine extension did the trick. The working line looks like:
from machine import I2C, Pin

Not sure, why this happens, but I definitely did not get the script running with the unmodified line.
