### ISSUE TITLE
course 1.4 notebook

### ISSUE THREAD

**Issue by programlich** [AccelerationConsortium/ac-microcourses#91]
Some details I noticed when working with `1.4.1-onboard-led-temp.ipynb`:
- The instructions tell to set up the Pi according to chapter one. There the secrets file was called `secrets.py`, in chapter 1.4 it's `my_secrets.py`. That's a bit confusing
- There is no indication explicitly telling, that the own Hivemq instance can be used, if already set up. In that case the second cell in the notebook needs to be adapted
- The temperature plot does not have axlabels. I suggest adding these, e.g. like:

```
    # Update the plot
    clear_output(wait=True)  # Clear the current output
    plt.plot(timestamps, onboard_temps)  # Plot the temperatures
    plt.xlabel("t (s)")
    plt.ylabel("T (°C)")
    plt.tight_layout()
    plt.show()  # Show the plot
```

**Comment by sgbaird** [comment]
> Some details I noticed when working with `1.4.1-onboard-led-temp.ipynb`:
> 
> * The instructions tell to set up the Pi according to chapter one. There the secrets file was called `secrets.py`, in chapter 1.4 it's `my_secrets.py`. That's a bit confusing
> * There is no indication explicitly telling, that the own Hivemq instance can be used, if already set up. In that case the second cell in the notebook needs to be adapted
> * The temperature plot does not have axlabels. I suggest adding these, e.g. like:
> 
> ```
>     # Update the plot
>     clear_output(wait=True)  # Clear the current output
>     plt.plot(timestamps, onboard_temps)  # Plot the temperatures
>     plt.xlabel("t (s)")
>     plt.ylabel("T (°C)")
>     plt.tight_layout()
>     plt.show()  # Show the plot
> ```

@SissiFeng I've been meaning to revamp tutorial 1.1, implementing essentially from scratch and removing the dependency on the build instructions manuscript (perhaps recording a new video, too). https://github.com/AccelerationConsortium/ac-microcourses/issues/82. This would be inline with the revamp too

**Comment by SissiFeng** [comment]
> > Some details I noticed when working with `1.4.1-onboard-led-temp.ipynb`:
> > 
> > * The instructions tell to set up the Pi according to chapter one. There the secrets file was called `secrets.py`, in chapter 1.4 it's `my_secrets.py`. That's a bit confusing
> > * There is no indication explicitly telling, that the own Hivemq instance can be used, if already set up. In that case the second cell in the notebook needs to be adapted
> > * The temperature plot does not have axlabels. I suggest adding these, e.g. like:
> > 
> > ```
> >     # Update the plot
> >     clear_output(wait=True)  # Clear the current output
> >     plt.plot(timestamps, onboard_temps)  # Plot the temperatures
> >     plt.xlabel("t (s)")
> >     plt.ylabel("T (°C)")
> >     plt.tight_layout()
> >     plt.show()  # Show the plot
> > ```
> 
> @SissiFeng I've been meaning to revamp tutorial 1.1, implementing essentially from scratch and removing the dependency on the build instructions manuscript (perhaps recording a new video, too). #82. This would be inline with the revamp too

Okay, I'll make a note to start working on the update.

**Comment by SissiFeng** [comment]
Modified.

**Comment by sgbaird** [comment]
@SissiFeng could you include a link to the relevant commit or PR?

**Comment by sgbaird** [comment]
Aside: @SissiFeng consider including the link to this issue in the commit message and/or link the issue to the corresponding PR (this will provide some breadcrumbs that make it easier to review)
