### ISSUE TITLE
Add robotics assignments #1-3

### ISSUE THREAD

**Issue by sgbaird** [AccelerationConsortium/ac-microcourses#94]
No need to worry about it until next week, but @linx5o pointed out that these ones are missing. My bad for not catching/mentioning sooner - I had only put some drafts of the tutorials for these up, not any assignments.

![Screenshot_20241012-173537.png](https://github.com/user-attachments/assets/2bfb70b9-06b0-46c7-adf1-f7df321d5422)

**Comment by SissiFeng** [comment]
I have these links added to my local repo, thinking pr them together when the 3.1-3.3 assignments go live.

**Comment by SissiFeng** [comment]
The repo, classroom, and self-report for all three assignments are added.
<img width="287" alt="截屏2024-10-15 18 10 51" src="https://github.com/user-attachments/assets/dcf7ab01-1b07-4b3c-8e37-860181cdb61c">
<img width="245" alt="截屏2024-10-15 18 10 40" src="https://github.com/user-attachments/assets/9cc2de93-412a-4410-86b3-a68dda85c3b8">

**Comment by sgbaird** [comment]
Thanks @SissiFeng! @linx5o could you take a look when you get a chance?

**Comment by sgbaird** [comment]
Same for @RubainaFarin31 and @Luthiraa

**Comment by linx5o** [comment]
The orientation course is not present on quercus.

The links have not been added to the site. I can create a pull request if needed.

**Comment by sgbaird** [comment]
Added orientation course (thanks for catching), can you add a PR for the links?

**Comment by sgbaird** [comment]
UPDATE: I had a couple things to do so I ended up fixing the links as well. Could you double check it for me @linx5o ?

**Comment by linx5o** [comment]
The orientation modules are not published its seems.
![image](https://github.com/user-attachments/assets/34dd0d26-edaa-44d9-b50c-659363e53bf4)
<br>
I have also added links for assignments 3.1, 3.2, 3.3, in pull request.
